### PR TITLE
Scroll compensation on zoom now happening in the same event loop.

### PR DESCRIPTION
**Pull request by rsedevnet**
This prevents flicking in Firefox.

### CODE REVIEW

**Review by ohommes — CHANGES_REQUESTED** [review]
Please don't check in your .swp files; Maybe vi left over. Always add only what is needed. Please remove them from this PR. I would cancel the PR and reset the commit because it should never be in your local repor either. Maybe add a .ignore to prevent this. Never stage with wildcards.

**Comment by ohommes** [comment]
Also when trying this use the following browsers to test/check:
Chrome, Edge, Firefox, Brave, Opera, Vivaldi, (and on MacOS add Safari if you have access to it)

the scale factor greatly improves this here. Please fix the patch as indicated so I can merge it

**Comment by rsedevnet** [comment]
> Please don't check in your .swp files; Maybe vi left over. Always add only what is needed. Please remove them from this PR. I would cancel the PR and reset the commit because it should never be in your local repor either. Maybe add a .ignore to prevent this. Never stage with wildcards.

Yeah, sorry, that's from ~20 years of having vi swap files in gitignore. New commits pushed. Squash on merge if you want a clean commit history?

My intention is to use this in an Android/iOS WebView, which means that I only need to care about Blink/WebKit support. I'll also be removing certain features that don't make sense on a mobile device and adding support for various touch events/gestures with (minified) jQuery, all of which you probably don't want in the desktop version. As such, I'll just continue with my forked version and submit occasional PRs if I think you might find something useful... though I leave the testing on the desktop browsers to you. :p

Of course you're more than welcome to pull whatever you like, as well.

https://github.com/rsedevnet/bms-maps

Cheers!

-Sean

**Comment by ohommes** [comment]
Ah cool; Yeah some people around me also said maybe make it a web-app on iOS. Look forward to it. Hope to get some good work back as you progress!

**Review by ohommes — APPROVED** [review]
All looks good now and tested it. No more flicker and with the scale better center keeping.

**Pull request merged**
