### PR TITLE
Map stays roughly centered when zooming in and out.

### PR DESCRIPTION
**Pull request by rsedevnet**

### CODE REVIEW

**Review by ohommes — APPROVED** [review]
Interesting deferred function!

**Comment by rsedevnet** [comment]
> Interesting deferred function!

Thanks! It gives the image resize a chance to "settle" before additional calculations are made (in the next event loop). Not strictly necessary in certain browsers, but it's a good safety precaution.

**Comment by ohommes** [comment]
@rsedevnet When you zoom in and zoom out fast there is a visible glitch rendered. I am guessing because the scroll is somewhat asynchronous. Have you tried just doing the inline and see if that improves things? 

I am planning to add scroll wheel zoom in and out or you can add that if you like with a step scale step size of 0.01 for the scroll wheel (properties.zoom -= 0.01 and properties.zoom += 0.01 for scroll wheel zoom in and out with the same zoom limits as today on line 830 and 835

**Comment by rsedevnet** [comment]
> @rsedevnet When you zoom in and zoom out fast there is a visible glitch rendered. I am guessing because the scroll is somewhat asynchronous. Have you tried just doing the inline and see if that improves things?
> 
> I am planning to add scroll wheel zoom in and out or you can add that if you like with a step scale step size of 0.01 for the scroll wheel (properties.zoom -= 0.01 and properties.zoom += 0.01 for scroll wheel zoom in and out with the same zoom limits as today on line 830 and 835

Yeah, darn. It was working fine in Chrome (no flickering), but Firefox... yeah, flicker.

Anyway, submitted a new pull request wherein everything happens in the same event loop (required a slightly different calculation). No more flicking in Firefox... for me, anyway. Chrome still works great as well.

I'll take a look at the scroll wheel zoom, sure. Probably not difficult. :-)

**Comment by ohommes** [comment]
I had the flicker in Chrome slightly.
The scroll wheel is easy but I didn't do it since I need the center to stay the same :)

**Pull request merged**
